FROM node:14.15.3-alpine
WORKDIR /usr/src/app
RUN npm install --save prop-types
RUN npm install -g create-react-app

# docker-compose build
# docker-compose run --rm node sh -c 'create-react-app front' nextならいらん
# docker-compose up